name: Update Pet Data
on:
  schedule:
    - cron: '0 0 * * 0'  # Jeden Sonntag um Mitternacht UTC
  workflow_dispatch:     # Manueller Trigger

jobs:
  update_pets:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Wichtig für git push
    
    steps:
    # 1. Repository auschecken
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0   # Für korrekte Git-Historie

    # 2. Python einrichten
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3. Abhängigkeiten installieren
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    # 4. Daten scrapen und konvertieren
    - name: Scrape and convert data
      run: |
        python petopia_scraper.py
        python json_to_lua.py
      
    # 5. Änderungen pushen
    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Dein Token aus Secrets
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin "https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}.git"
        git add .
        git commit -m "Automatisches Daten-Update $(date +'%Y-%m-%d')" || echo "Keine Änderungen"
        git push origin main
