name: Update Pet Data
on:
  workflow_dispatch:

jobs:
  update_pets:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests
        
    - name: Scrape data
      run: |
        python petopia_scraper.py
        echo "Scraped data:"
        jq '.[] | length' petopia_data.json
        [ $(jq '[.[] | length] | add' petopia_data.json) -gt 0 ] || exit 1
        
    - name: Generate Lua
      run: |
        python json_to_lua.py
        echo "First pet in Lua:"
        head -n 15 HRT_Data.lua
        
    - name: Commit changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin "https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}.git"
        git add .
        git diff --quiet && git diff --cached --quiet || git commit -m "Data update $(date +'%Y-%m-%d %H:%M')"
        git push origin main
