name: Update Pet Data
on:
  schedule:
    - cron: '0 0 * * 0'  # Sonntags um Mitternacht UTC
  workflow_dispatch:     # Manueller Trigger

jobs:
  update_pets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests
        
    - name: Scrape data
      run: python petopia_scraper.py
      
    - name: Verify scraped data
      run: |
        echo "Pets per category:"
        jq '.[] | length' petopia_data.json
        [ $(jq '[.[] | length] | add' petopia_data.json) -gt 0 ] || exit 1
        
    - name: Generate Lua
      run: python json_to_lua.py
      
    - name: Commit changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin "https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}.git"
        git add .
        git diff --quiet && git diff --cached --quiet || git commit -m "Auto-update $(date +'%Y-%m-%d %H:%M UTC')"
        git push origin main
